version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: justpath
    path: ./.github/config/justpath.dict
    addWords: true
dictionaries:
  - justpath
words: []
ignoreWords: []
import: []
