name: Python Build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-22.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install 'uv'
        uses: astral-sh/setup-uv@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-cache: false
          prune-cache: false
          python-version: ${{ matrix.python-version }}

      - run: uv build
      - run: uv run pytest
